apiVersion: apps/v1
kind: Deployment
metadata:
  name: webcilsy
  labels:
    app: webcilsy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webcilsy
  template:
    metadata:
      labels:
        app: webcilsy
    spec:
      containers:
      - name: webcilsy
        image: ajjaiii/webcilsy:$BUILD_NUMBER
        ports:
        - containerPort: 80
