apiVersion: apps/v1
kind: Deployment
metadata:
  name: webcilsypro
  labels:
    app: webcilsypro
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webcilsypro
  template:
    metadata:
      labels:
        app: webcilsypro
    spec:
      containers:
      - name: webcilsypro
        image: ajjaiii/webcilsypro:BUILD_NUMBER
        ports:
        - containerPort: 80
